MONGODB_HOST: mongodb.{{ env }}.aslearnings.online
REDIS_HOST: redis.{{ env }}.aslearnings.online
MYSQL_HOST: mysql.{{ env }}.aslearnings.online
RABBITMQ_HOST: rabbitmq.{{ env }}.aslearnings.online
CATALOGUE_HOST: catalogue.{{ env }}.aslearnings.online
USER_HOST: user.{{ env }}.aslearnings.online
CART_HOST: cart.{{ env }}.aslearnings.online
SHIPPING_HOST: shipping.{{ env }}.aslearnings.online
PAYMENT_HOST: payment.{{ env }}.aslearnings.online
DISPATCH_HOST: dispatcher.{{ env }}.aslearnings.online
FRONTEND_HOST: roboshop.{{ env }}.aslearnings.online
