- name: install golang packages
  package:
    name: golang
    state: present
- name: go mod init
  command: go mod init dispatch
  args:
    chdir: /app

- name: go get dependencies
  command: go get
  args:
    chdir: /app

- name: go build
  command: go build
  args:
    chdir: /app