- name: enable nodejs version 20
  command: dnf module enable nodejs:20 -y 

- name: install nodejs
  package:
    name: nodejs
    state: present

- name: install dependincies
  community.general.npm:
    path: /app